services:
  logs-db:
    container_name: economic-db
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: economic-db
    ports:
      - 5433:5432
