global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: economic-api
    static_configs:
      - targets: ["192.168.252.38:3000"]

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
